### ISSUE TITLE
I copied the whole zip file and also connected to the database, but when I try to login with the right input is fails. It says (incorrect username or password).)

### ISSUE THREAD

**Issue by ghost** [attilaantal/PHP-OOP-Login-Register-System#4]

**Comment by attilaantal** [comment]
The issue is related to character encodings. The random bytes before storing were different from the bytes fetched from the database.

I've added charset support for the PDO connection, so you can specify which charset should be used for the CRUD operations. 

This seems to fix the problem, however, I am thinking of improving the code by using an alternative method to encrypt the password, but probably I'll do that in a different fork. This way I can reserve the legacy PHP OOP Login Register System example.

**Comment by attilaantal** [comment]
I've updated the code by replacing the manual password encryption with PHP's built-in functions. This should not cause encoding issues.

>When using the default encryption algorithm (**PASSWORD_DEFAULT**), PHP recommends storing the passwords in a column that expands beyond 64 characters (255 would be ideal). You can read more on that in the [password_hash](https://www.php.net/manual/en/function.password-hash.php) article.

Commits:
- [replaced manual password encryption with password_hash function](https://github.com/attilaantal/PHP-OOP-Login-Register-System/commit/70dca6af60518b63d9104eac257c2b49234edce0)
- [update charset of the pdf connection](https://github.com/attilaantal/PHP-OOP-Login-Register-System/commit/fad556204a13a0eff1cc40dc7e77022ba65cdf31)
- [updated database script](https://github.com/attilaantal/PHP-OOP-Login-Register-System/commit/836523a117d3ffd13710297e075f1aff03527da9)
